### PR TITLE
Add the tree page

### LINKED ISSUE #3: Move some of the plugins to the other extensions
For now, most of the custom plugins live in the `application-extension`: https://github.com/jtpio/jupyterlab-classic/blob/main/packages/application-extension/src/index.ts

Some could be moved in different extensions, for example the ones that add kernel indicators to the shell.

This would prepare the ground to support the tree and terminal views later on.

### LINKED ISSUE #5: Add the tree view
For example by reusing the existing lab file browser and running components, put together in a stacked panel.

For reference:

image

### PR DESCRIPTION
**Pull request by jtpio**
Fixes #5 
Fixes #3 

### TODO

- [x] Open in a new browser tab
- [x] Handle double-clicks? (might require an upstream fix)
- [x] ~Add the running tab~ -> separate issue

open-notebook-new-tab

### CODE REVIEW

**Comment by yuvipanda** [comment]
Love the GIFs <3

**Comment by jtpio** [comment]
Thanks!

Looks like the double click event is hitting a limitation in the current file browser:

https://github.com/jupyterlab/jupyterlab/blob/d8d724335f24888a71a90c18d35e3b9a06365738/packages/filebrowser/src/listing.ts#L987

@yuvipanda I think you had a similar issue with the simplest notebook?

**Comment by jtpio** [comment]
> Add the running tab -> separate issue

Let's handle the running sessions in a separate PR.

**Comment by yuvipanda** [comment]
@jtpio haha, I did! :D

**Comment by jtpio** [comment]
This patch seems to be working quite well actually:

https://github.com/jtpio/jupyterlab-classic/blob/c3638b850bafccbd667b1b91bd461b9c22e96798/packages/docmanager-extension/src/index.ts#L29-L44

**Pull request merged**
